export const triggers: typeof trigger;
import * as trigger from "./trigger";
import * as instance from "./instance";
import * as applications from "./applications";
import * as file from "./file";
import * as folder from "./folder";
import * as note from "./note";
import * as account from "./account";
export const accounts: typeof account;
import * as permission from "./permission";
import * as utils from "./utils";
import * as contact from "./contact";
import * as document from "./document";
export { trigger, instance, applications, file, folder, note, account, permission, utils, contact, document };
